# drs_editor/gui/vis_job_data.py

VIS_JOB_MAP = {
    0: "Idle",
    1: "Walk",
    2: "Run",
    3: "Spawn",
    4: "HitFromBack",
    5: "Cheer / Emote",
    6: "SpellTargetShotSequenceAreaShotDelay / SpellTargetShotSequenceAreaIdle",
    7: "UnDeploy",
    8: "Attack",
    9: "Deploy / Charge Attack Run",
    10: "WormMovement Start",
    11: "HitFromFront",
    12: "Die",
    13: "CorpseRot",
    14: "SpellTargetShotSequenceAreaRecoil / HitFromLeft",
    15: "Special Melee Attack (AnimTagID 114)",
    16: "Special Melee Attack (AnimTagID 115)",
    17: "WormMovement Loop",
    18: "Cast",
    19: "CastResolve",
    21: "CastResolveAir",
    22: "CastAir",
    23: "HitFromRight",
    24: "Talk",
    27: "Impactful Movement / Trample",
    28: "WormMovement End",
    29: "PushBackStandUp Start",
    30: "PushBackStandUp Loop",
    31: "PushBackStandUp End",
    35: "Immobilized / Trapped",
    99: "Trailer",
    128: "StampedeStart",
    129: "StampedeRun",
    130: "StampedeStop",
    131: "EraseOverTimeInit / EraseOverTimeStart",
    132: "EraseOverTimeWork / EraseOverTimeLoop",
    133: "EraseOverTimeShutDown / EraseOverTimeEnd",
    134: "GroundPounder (Tremor) Cast",
    135: "GroundPounder (Tremor) Resolve",
    136: "Firelance (Emberstrike) Cast",
    137: "Firelance (Emberstrike) Resolve",
    138: "Paralyze Cast",
    139: "Paralyze Resolve",
    140: "ThrowFlames Init",
    141: "ThrowFlames Work",
    142: "ThrowFlames ShutDown",
    143: "ThrowShadowFlames Init",
    144: "ThrowShadowFlames Work",
    145: "ThrowShadowFlames ShutDown",
    146: "Conflagration Init",
    147: "Conflagration Work",
    148: "Conflagration ShutDown",
    149: "Exhaust Cast",
    150: "Exhaust Resolve",
    151: "UnholyArmor Cast",
    152: "UnholyArmor Resolve",
    153: "Frenzy Cast",
    154: "Frenzy Resolve",
    155: "SummonSkeletons Cast",
    156: "SummonSkeletons Resolve",
    157: "Deathwish Cast",
    158: "Deathwish Resolve",
    159: "SacrificeSquad Cast",
    160: "SacrificeSquad Resolve",
    161: "SuicidalBomb Cast",
    162: "SuicidalBomb Resolve",
    163: "CrushWalls Cast",
    164: "CrushWalls Resolve",
    165: "Rage (AnimTagID 31)",
    166: "Rage (AnimTagID 32)",
    167: "DisableTower Cast",
    168: "DisableTower Resolve",
    169: "PowerSteal Cast",
    170: "PowerSteal Resolve",
    173: "Heal Cast",
    174: "Heal Resolve",
    175: "ThunderousRoar Cast",
    176: "ThunderousRoar Resolve",
    177: "Heal Channel Start",
    178: "Heal Channel Loop",
    179: "Heal Channel End",
    180: "Paralyze Channel Start",
    181: "Paralyze Channel Loop",
    182: "Paralyze Channel End",
    183: "DisableTower CastAir",
    184: "DisableTower ResolveAir",
    185: "PreparedSalvo Cast",
    186: "PreparedSalvo Resolve",
    187: "PreparedSalvo CastAir",
    188: "PreparedSalvo ResolveAir",
    189: "Special Burrow Cast",
    190: "Special Burrow Resolve",
    191: "Turret Fire To Front Cast",
    192: "Turret Fire To Front Resolve",
    193: "Turret Fire To Left Cast",
    194: "Turret Fire To Left Resolve",
    195: "Turret Fire To Back Cast",
    196: "Turret Fire To Back Resolve",
    197: "Turret Fire To Right Cast",
    198: "Turret Fire To Right Resolve",
    199: "Charge Attack",
    200: "SummonDemon Cast",
    201: "SummonDemon Resolve",
    202: "AreaFreeze Cast",
    203: "AreaFreeze Resolve",
    204: "HealingRay Cast",
    205: "HealingRay Resolve",
    206: "IceShield Channel Start (Previously Winter Witch aura)",
    207: "IceShield Channel Loop",
    208: "IceShield Channel End",
    209: "FrostBeam Start",
    210: "FrostBeam Loop",
    211: "FrostBeam End",
    212: "AntimagicField Start",
    213: "AntimagicField Loop",
    214: "AntimagicField End",
    215: "FireStream Start",
    216: "FireStream Loop",
    217: "FireStream End",
    218: "StasisField Cast",
    219: "StasisField Resolve",
    220: "BurningLiquid Cast",
    221: "BurningLiquid Resolve",
    222: "MindControl Cast",
    223: "MindControl Resolve",
    224: "IceShield Target Cast",
    225: "IceShield Target Resolve",
    226: "SonicScream Cast",
    227: "SonicScream Resolve",
    228: "TeleportSelf Cast",
    229: "TeleportSelf Resolve",
    230: "Repair Channel Start (AnimTagID 110)",
    231: "Repair Channel Loop (AnimTagID 110)",
    232: "Repair Channel End (AnimTagID 110)",
    233: "Strike Cast",
    234: "Strike Resolve",
    235: "CriticalMass Cast",
    236: "CriticalMass Resolve",
    237: "SiegeTrumpet Cast",
    238: "SiegeTrumpet Resolve",
    239: "Bracing Zone Cast",
    240: "Bracing Zone Resolve",
    241: "Fireball Cast",
    242: "Fireball Resolve",
    243: "MassSleep Cast",
    244: "MassSleep Resolve",
    245: "ChainInsectRay Cast",
    246: "ChainInsectRay Resolve",
    247: "Repair Channel Start (AnimTagID 121)",
    248: "Repair Channel Loop (AnimTagID 121)",
    249: "Repair Channel End (AnimTagID 121)",
    250: "BombRaid Cast",
    251: "BombRaid Resolve",
    252: "LifeLink Start",
    253: "LifeLink Loop",
    254: "LifeLink End",
    255: "WormMovement_Hack Cast",
    256: "WormMovement_Hack Resolve",
    257: "skel_giant_hammer_attack_pve1 Cast",
    258: "skel_giant_hammer_attack_pve1 Resolve",
    259: "IceBombardment Near Start",
    260: "IceBombardment Near Loop",
    261: "IceBombardment Near End",
    262: "IceBombardment Far Start",
    263: "IceBombardment Far Loop",
    264: "IceBombardment Far End",
    265: "ParalyzingRoar Cast",
    266: "ParalyzingRoar Resolve",
    267: "SacrificeKill Cast",
    268: "SacrificeKill Resolve",
    269: "LifeTransfer Cast",
    270: "LifeTransfer Resolve",
    271: "Earthquake Start",
    272: "Earthquake Loop",
    273: "Earthquake End",
    274: "PVEChannel Start",
    275: "PVEChannel Loop",
    276: "PVEChannel End",
    277: "PVECastResolve Cast",
    278: "PVECastResolve Resolve",
    279: "PVEMelee Attack",
    280: "AttachToBuilding Start",
    281: "AttachToBuilding Loop",
    282: "AttachToBuilding End",
    283: "RepairCast Cast",
    284: "RepairCast Resolve",
    285: "RageCastStage1 Cast",
    286: "RageCastStage1 Resolve",
    287: "RageCastStage1 CastAir",
    288: "RageCastStage1 ResolveAir",
    289: "RageCastStage2 Cast",
    290: "RageCastStage2 Resolve",
    291: "RageCastStage2 CastAir",
    292: "RageCastStage2 ResolveAir",
    293: "SuicideAttack Cast",
    294: "SuicideAttack Resolve",
    295: "RelocateBuilding Cast",
    296: "RelocateBuilding Resolve",
    297: "DeathCounter Cast",
    298: "DeathCounter Resolve",
    299: "TombOfDeath Start",
    300: "TombOfDeath Loop",
    301: "TombOfDeath End",
    302: "VersatileAirSpecial Cast",
    303: "VersatileAirSpecial Resolve",
    304: "PVECastResolve2 Cast",
    305: "PVECastResolve2 Resolve",
    306: "Taunt Cast",
    307: "Taunt Resolve",
    308: "Swap Cast",
    309: "Swap Resolve",
    310: "Disenchant Cast",
    311: "Disenchant Resolve",
    312: "GravitySurge Cast",
    313: "GravitySurge Resolve",
    314: "Enrage Cast",
    315: "Enrage Resolve",
    316: "SpecialRangedAir Cast",
    317: "SpecialRangedAir Resolve",
    318: "GlobalBuffChannel Start",
    319: "GlobalBuffChannel Loop",
    320: "GlobalBuffChannel End",
    321: "Harpoon Cast",
    322: "Harpoon Resolve",
    323: "ThrowMines Cast",
    324: "ThrowMines Resolve",
}
